name: rhkr8521 CI

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-22.04 

    steps: 
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: create application.yml
      run: |
        ## create application.yml
        mkdir -p ./ChargeControlBackend/src/main/resources
        echo "${{ secrets.CI_APPLICATION }}" > ./ChargeControlBackend/src/main/resources/application.yml

    - name: build
      run: |
        chmod +x ./ChargeControlBackend/gradlew
        ./ChargeControlBackend/gradlew build --project-dir ./ChargeControlBackend -x test
      shell: bash

    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chargecontrol_backend .
      # Dockerfile과 빌드 컨텍스트가 모두 루트 디렉토리에 있도록 설정
      working-directory: ./

    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: docker Hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/chargecontrol_backend
