name: rhkr8521 CICD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Create application.yml
      run: |
        mkdir -p ChargeControlBackend/src/main/resources
        echo "${{ secrets.CI_APPLICATION }}" > ChargeControlBackend/src/main/resources/application.yml

    - name: Build with Gradle
      run: ./gradlew build -p ChargeControlBackend

    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chargecontrol_backend -f ChargeControlBackend/Dockerfile ChargeControlBackend

    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: docker Hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/chargecontrol_backend
